### ISSUE TITLE
Triggering Alarm moves GUI

### ISSUE THREAD

**Issue by theswede402** [adhansen/wilderness-player-alarm#42] opened 2024-07-18 15:17 UTC
As of this morning (7/18/2024, about 8:30 AM Central Standard Time) a triggered alarm moves the plugin information in the upper left corner of Rune Lite down to the bottom left corner. Clearing the alarm moves things back, but as soon as the alarm triggers again, the UI components get moved again. This wasn't happening 12 hours ago but just started happening when I logged in this morning.
![rune lite wilderness bug](https://github.com/user-attachments/assets/9ae0f974-2f24-4243-ae41-b0fa65b4d196)

**Comment by adhansen** [comment] 2024-07-18 16:21
Alright I'll do this with #41. I didn't think to test plugin interoperability like this when I brought back the AlarmOverlay (with significant code changes).

This probably has to do with the layer that it's rendered on.
https://github.com/adhansen/plugin-repo/blob/WildernessPlayerAlarm/release/src/main/java/com/WildernessPlayerAlarm/AlarmOverlay.java#L21

I will wait a few days for people to open any other issues they find with the rollback.

**Comment by Bizank0** [comment] 2024-07-19 06:01
+1, my info just disappears entirely

**Comment by adhansen** [comment] 2024-07-19 07:54
@theswede402 I'm unable to reproduce this, would you be able to share your plugin configuration? Also, are you on Windows?
![image](https://github.com/user-attachments/assets/514578e1-1f9b-4a42-90dc-2dd4ad3ee18c)

**Comment by theswede402** [comment] 2024-07-19 13:50
Sure; plugin details provided here. I am on Windows 11.

![image](https://github.com/user-attachments/assets/373ee19c-210d-45ea-ab56-a7b566c744d0)
![image](https://github.com/user-attachments/assets/d31d5fde-22da-45e6-acbc-5b0310082eae)

I am also using the Stretched Mode setting, with the following settings, but was also using this two days ago before this issue started to happen:

![image](https://github.com/user-attachments/assets/381a31b3-d9d2-43e7-a18d-b2765a228fe8)

**Comment by rednewt812** [comment] 2024-09-22 16:56
Also been experiencing the same issue since at least around Aug 20, settings attached 
![image](https://github.com/user-attachments/assets/95b95fd8-d657-4079-88c6-f3aa6bcea03e)

**Comment by adhansen** [comment] 2024-09-22 23:48
I'm surprised that it's happening with the notification overrides' flash and not the plugin's own. I'm still unable to reproduce this. Are you seeing the same bug when the idle notifier activates?

**Comment by rednewt812** [comment] 2024-09-23 20:45
I actually did observe this with idle notifier after testing it but haven't been able to reproduce it consistently. It does seem like it's tied to the notification system I guess.

**Comment by adhansen** [comment] 2024-11-03 01:30
@theswede402 (or anyone else who experienced this issue) would you be able to verify that it still reproduces? The above PR has merged to the hub which contains a fix for #41, which may have been the root cause of this issue.

**Comment by adhansen** [comment] 2024-11-22 03:50
There were some insight into this from the above issue, and I was able to repro this with the config provided in that thread. It turns out this issue does have to do with the layer that the plugin is rendered on. The current default of `OverlayLayer.ABOVE_SCENE` is the same layer that the ping grapher widget is drawn on, so the graph gets pushed out when the alarm overlay is rendered covering the whole screen.
I do prefer the 'above scene' layer because it keeps the inventory and chatbox in its true color, so I'm going to add another config option that allows user control of this behavior which should be a way to resolve this problem
![image](https://github.com/user-attachments/assets/15570cfc-f133-425b-8a48-1cef263e285e)

**Closed as completed** 2024-12-31 02:23 UTC
Labels: bug, help wanted, wilderness player alarm
