### ISSUE TITLE
Plugin not working - Wilderness player alarm 

### ISSUE THREAD

**Issue by Dorchmund** [adhansen/wilderness-player-alarm#39] opened 2024-07-11 23:25 UTC
This plugin stopped working for me like 2 hours ago. It just stopped flashing whenever someone approaches me.

It was working while i was doing some artio for wildy slayer, and it suddently stopped, cant solve it by removing and reinstalling, cant find much about it, just 2 threads on this same issue from today, hope someone finds a solution i will appreciate it! I didnt install any new plugin when this happened so cant think about some plugin compatibility or something like that

**Comment by Dorchmund** [comment] 2024-07-11 23:29
![image](https://github.com/user-attachments/assets/527c9e34-2ddb-40fc-be05-bf59be66f204)


I noticed by reading another thread on this topic, that my plugin settings is also different from other players, whos plugins are working, theres no flash color bar underneath the other options

**Comment by Postieyeet** [comment] 2024-07-12 01:26
Hey big dog had the same problem if you go into the notification settings and your flash is set to "off" hit the drop down menu and put it back to "flash until cancelled" should be back to normal.

**Comment by Dream3rz** [comment] 2024-07-12 01:57
> Hey big dog had the same problem if you go into the notification settings and your flash is set to "off" hit the drop down menu and put it back to "flash until cancelled" should be back to normal.

This doesn't work. I had tried this before I posted here

**Comment by Postieyeet** [comment] 2024-07-12 01:59
> > Hey big dog had the same problem if you go into the notification settings and your flash is set to "off" hit the drop down menu and put it back to "flash until cancelled" should be back to normal.
> 
> This doesn't work. I had tried this before I posted here

Thats weird man its been working for me... Sorry i couldnt help.

**Comment by adhansen** [comment] 2024-07-12 02:18
Some of the settings were moved around with the last update, discussed in #38

But the plugin should still be working otherwise, I just did a quick sanity-check by the chaos altar on release runelite version and it still went off.

Your settings may have been wiped with the update (apologies for the disruption)- can you verify that and see if the issue persists? I rewrote pretty much the whole plugin so I would believe there is a bug too. For one, the plug-in used to track each player in range and go off again if another player shows up. Now, if there is another player in range and someone else shows up it won't go off. Is that a problem you're having?

**Comment by Dorchmund** [comment] 2024-07-12 02:46
Hello! Thank you for your answer!

No, its still not working, i already tried opening the settings next to notifications and turning that option on, and also tried the other options available and they didnt work either.
What do you mean that my settings might have been wiped? My plugin settings or which ones? Ill send a screenshot of my plugin settings just in case.

And no, the problem that im having is that the alarm is never triggering, even when only one person shows up..

![image](https://github.com/user-attachments/assets/1b1eeec9-9db2-4284-8f74-326c6c90b96f)

**Comment by adhansen** [comment] 2024-07-12 02:48
@Dorchmund you'll need to check "Send notifications when focused"

**Comment by Dorchmund** [comment] 2024-07-12 03:15
Allright, that worked.. Thank you <3 Great plugin happy i can still use it :)

**Comment by adhansen** [comment] 2024-07-12 03:21
Glad we got it figured out! I'm going to leave this and #38 open for a while for others to see because I've clearly caused some usability regression, nevermind the bug I mentioned above (which I'm also working on fixing at this moment).

**Comment by Bizank0** [comment] 2024-07-12 03:22
Yeah, something is bugged out with this plugin.

It doesn't matter if I use customized settings or the native RL ones. I now have flash set to 'until cancelled', it was originally set to 'off' when I had discovered the plugin wasn't working earlier today.  

Unsure of what my settings were before this problem occurred, but the plugin would nonstop flash until the player went away and when a new player came into view, flashing would resume. Now when I focus my alt's client that I use to scout, the flashing stops. If I don't focus the client, the flashing continues even after the player has left. The first player I see, I get the flash but once I cancel the flash and when that player is gone and a new player arrives, there is no flash.

**Comment by adhansen** [comment] 2024-07-12 03:26
> it was originally set to 'off' when I had discovered the plugin wasn't working earlier today.

A side-effect of the interface rewrite. One of the individuals who requested notification overrides (#28) PR'd a change that would have migrated settings better to cause less disruption which I didn't bring in. Alas, what's done is done.

> The first player I see, I get the flash but once I cancel the flash and when that player is gone and a new player arrives, there is no flash.

Yep, definitely a bug. Working on this now, will track in this issue number.

**Comment by Bizank0** [comment] 2024-07-12 03:37
> Yep, definitely a bug. Working on this now, will track in this issue number.

Update: New players are being detected now even after I've cancelled flashing.

**Comment by Bizank0** [comment] 2024-07-12 03:58
@adhansen I know you're probably still working on the plugin but will I be able to have the plugin how I had it before the issue, with flashing until players are gone instead of flash until cancelled or flash for 2 seconds? Not a fan of these latter options.

**Comment by adhansen** [comment] 2024-07-12 04:00
@Bizank0 Short of building the old version from source, In the short term you could set the notification timeout to a very high value

**Comment by jeremyCreagan** [comment] 2024-07-12 05:05
> @Bizank0 Short of building the old version from source, In the short term you could set the notification timeout to a very high value

Addition to what @Bizank0 said. I'm at Chaos Alter and "flash until cancelled" has the same behavior has "flash for 2 seconds" If the game client is in focus. Both settings are only flashing for 2 seconds. 

Where as I would like it to continue flashing until the timeout or the player is out of range.

**Comment by infusion1** [comment] 2024-07-12 05:54
The new changes are great for the people who have requested it. However can we please also have an option that functions similar to how the old version functioned? 

Additional option:
"Flash until no player is within radius or Timeout counter is reached"

**Comment by adhansen** [comment] 2024-07-12 06:05
OK, I don't want to roll back notification overrides but I hear y'all on bringing back the 'flash until no player is within radius' functionality. I'm not entirely sure what the best way to bring that back is now that the flashing is implemented externally. It doesn't look like there's a way to stop the flashing with custom logic: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/Notification.java

This might require opening a feature request/PR in the main RuneLite repository unless I'm missing something obvious. There might be an uglier solution of extending the above class or the FlashNotification enum it contains, within this project, to have a "Flash until alone" enumeration. Maybe that's not such a bad way to proceed actually. I'll have to think about how to do this and how to not commit a usability gaffe.

Anyway I've opened a PR into the plugin hub to hotfix the regression of additional players not re-triggering the alarm from today's update: https://github.com/runelite/plugin-hub/pull/6276

**Comment by alexgermann** [comment] 2024-07-12 16:35
> OK, I don't want to roll back notification overrides but I hear y'all on bringing back the 'flash until no player is within radius' functionality. I'm not entirely sure what the best way to bring that back is now that the flashing is implemented externally. 

@adhansen Forgive my naivety, but could you just have a setting for "Use Original Notification" at the base setting level (rather than within the Notification sub settings)? That would allow you to put your original code back in to be used if that setting is checked. If it wasn't checked, it could still use the Runelite notification tie-in that I assume it's using now. 

I also much prefer the original flash until player leaves radius functionality!

**Comment by adhansen** [comment] 2024-07-12 17:53
@alexgermann 
> That would allow you to put your original code back in to be used if that setting is checked

Yes that would work, but I don't particularly want to add the old overlay back in if I don't have to. Anyway, the PR into plugin-hub to release acf721f is merged now so that bug isn't live anymore. I won't be able to work on the 'flash until no player is within radius' support this weekend but I'll think about it some more and get to it next week.

**Comment by cbenitezu** [comment] 2024-07-13 06:19
This plugin used to be perfect. Now its.... complicated and full of bugs.

I have flash "until cancelled" and it always flashes for 2 seconds, even though i have it set for 10.000 miliseconds. Also, transparency is not working on flash.
Maybe it cancels when i come back to runeline from chrome? But i dont want that, i liked when it flashed for 10 seconds no matter what. Did the plugin had issues? Was anyone complaining? Why "fix" what is working perfectly fine....?

**Comment by adhansen** [comment] 2024-07-13 17:31
Alright, enough people have complained about this that I'm seriously considering just rolling the notification overrides update back and poaching the 'play a sound' functionality in its place. I've seen the Reddit threads. The old interface was more usable as well.

I'll leave the discussion open over the weekend to give a chance for people to voice opposition to doing this. Barring that, I will try to make the change next week. $11.

**Comment by Hairfagri** [comment] 2024-07-15 10:35
> Alright, enough people have complained about this that I'm seriously considering just rolling the notification overrides update back and poaching the 'play a sound' functionality in its place. I've seen the Reddit threads. The old interface was more usable as well.
> 
> I'll leave the discussion open over the weekend to give a chance for people to voice opposition to doing this. Barring that, I will try to make the change next week. $11.

Please roll the plugin back to how it was.
It was perfect as it was.

**Comment by adhansen** [comment] 2024-07-16 03:31
Okay I think I have a change that will make everyone happy, I've rolled back the old interface save the boolean option "Desktop Notification" which will be replaced with a "Customizable Notification" that integrates notification overrides as requested in #28:
![image](https://github.com/user-attachments/assets/59c85779-d1bb-4769-9d2b-7fb5caf6069c)

![image](https://github.com/user-attachments/assets/c843b841-02a2-45a2-b56b-9da1400e5702)

By disabling flash within the customizable notification, the plugin can be configured exactly as it was before. I wanted to keep this as an option though for the people who requested it and its built-in ability to play sound. Plus who knows, maybe there are some users who prefer the flashing as its implemented in RuneLite notifications (either way will be an option).

The change is on a branch at https://github.com/adhansen/plugin-repo/tree/WildernessPlayerAlarm/notifications_rollback
I'll update again when the PR into plugin hub is live. There are a few more things I want to do, as well as test everything thoroughly.

**Comment by adhansen** [comment] 2024-07-17 06:14
PR for the rollback is up: https://github.com/runelite/plugin-hub/pull/6314

Please don't bother the RuneLite maintainers about it. Wilderness Player Alarm drama is not their fault, nor is it their problem

**Closed as completed** 2024-07-18 07:18 UTC
Labels: bug, enhancement, question, wilderness player alarm
